### ISSUE TITLE
Item height

### ISSUE THREAD

**Issue by ngmiduc** [tonix-tuft/react-really-simple-infinite-scroll#1]
Hi,

thats an interesting component. 
I try it out but does this inverse scroll also work when the item height is not fixed ? I am getting some weird loading behaviours and scroll height shifts.

best,

**Comment by tonix-tuft** [comment]
Hi @ngmiduc 👋,

this component doesn't make any assumptions about the height of the rendered children/items. They can have any height.

What's your use case and how are you using this component? Show me the code and I'll try to help 😉 .

Look forward to hearing from you!

**Comment by tonix-tuft** [comment]
I plan to close this issue if idle. As I said this component doesn't make any assumption regarding the height of the items, it doesn't care if one of your items is 100px or 5000px tall, and it is supposed to work in the same way both when displayInverse is `true` or `false` (default).

**Comment by ngmiduc** [comment]
Hello,
Thanks for reply.
Thanks it is working now for me too. I was just wondering if the component makes that assumption or not.

**Comment by tonix-tuft** [comment]
Hi @ngmiduc,

great! Glad that you was able to make it work! 😀

Don't forget to star this component if you find it useful! 😉
