### ISSUE TITLE
function not run

### ISSUE THREAD

**Issue by kaialsh705** [tonix-tuft/react-really-simple-infinite-scroll#2]
![Screenshot 2022-01-19 at 5 43 18 PM](https://user-images.githubusercontent.com/59761075/150127523-7ada1b9a-5f91-4f61-9302-0c080f719318.png)

**Comment by kaialsh705** [comment]
this.fetchMoreData function not working,
what i wrong please help.

**Comment by tonix-tuft** [comment]
Hi @kaialsh705,

Please, share me the code and not a screenshot of the code. Also, I need to see how you are using the component (how and when you set the state).

**Comment by tonix-tuft** [comment]
> this.fetchMoreData function not working, what i wrong please help.

`onInfiniteLoad` is triggered provided that `isInfiniteLoading` is `false`, `hasMore` is `true` and you scroll up if you use `displayInverse` set to `true` or down if `displayInverse` is `false` (default).

Check out the example code provided in the README (it renders the same component you see in the GIF in the README, though in the GIF the component has also some CSS styles applied, but that's not important).

**Comment by tonix-tuft** [comment]
@kaialsh705 Did you solve it?

**Comment by kaialsh705** [comment]
Thank you bro
